# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cockomat(object):
    def setupUi(self, cockomat):
        cockomat.setObjectName("cockomat")
        cockomat.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        cockomat.setEnabled(True)
        cockomat.resize(800, 480)
        cockomat.setMaximumSize(QtCore.QSize(800, 480))
        cockomat.setBaseSize(QtCore.QSize(800, 480))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        cockomat.setFont(font)
        cockomat.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(cockomat)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 67, 320, 381))
        self.listWidget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.listWidget.setLineWidth(1)
        self.listWidget.setMidLineWidth(0)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(470, 67, 320, 331))
        self.listWidget_2.setObjectName("listWidget_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 10, 79, 25))
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAlphabetically)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("-")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 77, 25))
        self.pushButton.setObjectName("pushButton")
        cockomat.setCentralWidget(self.centralwidget)

        self.retranslateUi(cockomat)

        QtCore.QMetaObject.connectSlotsByName(cockomat)

    def retranslateUi(self, cockomat):
        _translate = QtCore.QCoreApplication.translate
        cockomat.setWindowTitle(_translate("cockomat", "Cock-o-mat"))
        self.pushButton.setText(_translate("cockomat", "Alle"))
